# Define the workflow's name
name: "Build and Test"
# Triggered after push, pull_request and workflow_dispatch events
on: [push, pull_request, workflow_dispatch]

# Define the environment variables
env:
  FAIL_FAST: 0
  SHOW_ERROR_DETAIL: 1

jobs:
  build-source:
    name: "Build Source Code"
    runs-on: ubuntu-latest
    env:
      # The default JDK version
      JDK_VER: 8
    outputs:
      version: ${{ steps.capa-version.outputs.version }}
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v2
        with:
          path: capa
      - name: "Set up OpenJDK ${{ env.JDK_VER }}"
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VER }}
      - name: "Cache local Maven repository"
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: "Cache capa"
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/group/rxcloud/capa
          key: ${{ runner.os }}-capa-snapshot-${{ github.sha }}
      - name: "Build capa"
        run: |
          cd ${{ github.workspace }}/capa
          mvn clean
          mvn compile -q
      - name: "Pack checkstyle file if failure"
        if: failure()
        run: 7z a ${{ github.workspace }}/checkstyle.zip *checkstyle* -r
      - name: "Upload checkstyle file if failure"
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: "checkstyle-file"
          path: ${{ github.workspace }}/checkstyle.zip

  unit-test:
    needs: [ build-source ]
    name: "Unit Test On ${{ matrix.os }} (OpenJDK: ${{ matrix.jdk }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 8, 11 ]
    env:
      DISABLE_FILE_SYSTEM_TEST: true
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v2
        with:
          path: capa
      - name: "Set up OpenJDK ${{ matrix.jdk }}"
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - uses: actions/cache@v2
        name: "Cache local Maven repository"
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Unit Test"
        timeout-minutes: 10
        run: |
          cd ${{ github.workspace }}/capa
          mvn test -q
      - name: "Upload Unit Test Coverage"
        uses: codecov/codecov-action@v1